// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(BitwardenUserCryptoManagementFFI)
import BitwardenUserCryptoManagementFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_bitwarden_user_crypto_management_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_bitwarden_user_crypto_management_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureBitwardenUserCryptoManagementInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Sub-client for configuring PIN unlock behavior.
 */
public protocol PinSettingsClientProtocol: AnyObject, Sendable {
    
    /**
     * Returns the configured PIN lock type, if a PIN lock is set.
     */
    func getLockType() async  -> PinLockType?
    
    /**
     * Returns the currently configured PIN, if available.
     */
    func getPin() async  -> String?
    
    /**
     * Returns the current status of PIN unlock
     */
    func getStatus() async  -> PinUnlockStatus
    
    /**
     * Sets or updates the account PIN and stores the corresponding unlock state.
     *
     * The `lock_type` determines how PIN unlock behaves for this account.
     * Returns an error when the PIN-protected state cannot be persisted.
     */
    func setPin(pin: String, lockType: PinLockType) async throws 
    
    /**
     * Unenrolls from PIN-based unlock
     */
    func unsetPin() async 
    
    /**
     * Validates whether `pin` matches the currently configured unlock PIN.
     */
    func validatePin(pin: String) async  -> Bool
    
}
/**
 * Sub-client for configuring PIN unlock behavior.
 */
open class PinSettingsClient: PinSettingsClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_bitwarden_user_crypto_management_fn_clone_pinsettingsclient(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_bitwarden_user_crypto_management_fn_free_pinsettingsclient(handle, $0) }
    }

    

    
    /**
     * Returns the configured PIN lock type, if a PIN lock is set.
     */
open func getLockType()async  -> PinLockType?  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_user_crypto_management_fn_method_pinsettingsclient_get_lock_type(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_bitwarden_user_crypto_management_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_user_crypto_management_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_user_crypto_management_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypePinLockType.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Returns the currently configured PIN, if available.
     */
open func getPin()async  -> String?  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_user_crypto_management_fn_method_pinsettingsclient_get_pin(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_bitwarden_user_crypto_management_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_user_crypto_management_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_user_crypto_management_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionString.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Returns the current status of PIN unlock
     */
open func getStatus()async  -> PinUnlockStatus  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_user_crypto_management_fn_method_pinsettingsclient_get_status(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_bitwarden_user_crypto_management_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_user_crypto_management_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_user_crypto_management_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypePinUnlockStatus_lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Sets or updates the account PIN and stores the corresponding unlock state.
     *
     * The `lock_type` determines how PIN unlock behaves for this account.
     * Returns an error when the PIN-protected state cannot be persisted.
     */
open func setPin(pin: String, lockType: PinLockType)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_user_crypto_management_fn_method_pinsettingsclient_set_pin(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(pin),FfiConverterTypePinLockType_lower(lockType)
                )
            },
            pollFunc: ffi_bitwarden_user_crypto_management_rust_future_poll_void,
            completeFunc: ffi_bitwarden_user_crypto_management_rust_future_complete_void,
            freeFunc: ffi_bitwarden_user_crypto_management_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypePinSettingsError_lift
        )
}
    
    /**
     * Unenrolls from PIN-based unlock
     */
open func unsetPin()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_user_crypto_management_fn_method_pinsettingsclient_unset_pin(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_bitwarden_user_crypto_management_rust_future_poll_void,
            completeFunc: ffi_bitwarden_user_crypto_management_rust_future_complete_void,
            freeFunc: ffi_bitwarden_user_crypto_management_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
    /**
     * Validates whether `pin` matches the currently configured unlock PIN.
     */
open func validatePin(pin: String)async  -> Bool  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_user_crypto_management_fn_method_pinsettingsclient_validate_pin(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(pin)
                )
            },
            pollFunc: ffi_bitwarden_user_crypto_management_rust_future_poll_i8,
            completeFunc: ffi_bitwarden_user_crypto_management_rust_future_complete_i8,
            freeFunc: ffi_bitwarden_user_crypto_management_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: nil
            
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePinSettingsClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = PinSettingsClient

    public static func lift(_ handle: UInt64) throws -> PinSettingsClient {
        return PinSettingsClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: PinSettingsClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PinSettingsClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PinSettingsClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePinSettingsClient_lift(_ handle: UInt64) throws -> PinSettingsClient {
    return try FfiConverterTypePinSettingsClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePinSettingsClient_lower(_ value: PinSettingsClient) -> UInt64 {
    return FfiConverterTypePinSettingsClient.lower(value)
}






/**
 * Client for managing the cryptographic machinery of a user account, including key-rotation.
 */
public protocol UserCryptoManagementClientProtocol: AnyObject, Sendable {
    
    /**
     * Returns the PIN settings sub-client.
     */
    func pinSettings()  -> PinSettingsClient
    
}
/**
 * Client for managing the cryptographic machinery of a user account, including key-rotation.
 */
open class UserCryptoManagementClient: UserCryptoManagementClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_bitwarden_user_crypto_management_fn_clone_usercryptomanagementclient(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_bitwarden_user_crypto_management_fn_free_usercryptomanagementclient(handle, $0) }
    }

    

    
    /**
     * Returns the PIN settings sub-client.
     */
open func pinSettings() -> PinSettingsClient  {
    return try!  FfiConverterTypePinSettingsClient_lift(try! rustCall() {
    uniffi_bitwarden_user_crypto_management_fn_method_usercryptomanagementclient_pin_settings(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUserCryptoManagementClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = UserCryptoManagementClient

    public static func lift(_ handle: UInt64) throws -> UserCryptoManagementClient {
        return UserCryptoManagementClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: UserCryptoManagementClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserCryptoManagementClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: UserCryptoManagementClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserCryptoManagementClient_lift(_ handle: UInt64) throws -> UserCryptoManagementClient {
    return try FfiConverterTypeUserCryptoManagementClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserCryptoManagementClient_lower(_ value: UserCryptoManagementClient) -> UInt64 {
    return FfiConverterTypeUserCryptoManagementClient.lower(value)
}




public struct PasswordChangeAndRotateUserKeysRequest: Equatable, Hashable {
    public let oldPassword: String
    public let password: String
    public let hint: String?
    public let trustedEmergencyAccessPublicKeys: [PublicKey]
    public let trustedOrganizationPublicKeys: [PublicKey]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(oldPassword: String, password: String, hint: String?, trustedEmergencyAccessPublicKeys: [PublicKey], trustedOrganizationPublicKeys: [PublicKey]) {
        self.oldPassword = oldPassword
        self.password = password
        self.hint = hint
        self.trustedEmergencyAccessPublicKeys = trustedEmergencyAccessPublicKeys
        self.trustedOrganizationPublicKeys = trustedOrganizationPublicKeys
    }

    

    
}

#if compiler(>=6)
extension PasswordChangeAndRotateUserKeysRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePasswordChangeAndRotateUserKeysRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PasswordChangeAndRotateUserKeysRequest {
        return
            try PasswordChangeAndRotateUserKeysRequest(
                oldPassword: FfiConverterString.read(from: &buf), 
                password: FfiConverterString.read(from: &buf), 
                hint: FfiConverterOptionString.read(from: &buf), 
                trustedEmergencyAccessPublicKeys: FfiConverterSequenceTypePublicKey.read(from: &buf), 
                trustedOrganizationPublicKeys: FfiConverterSequenceTypePublicKey.read(from: &buf)
        )
    }

    public static func write(_ value: PasswordChangeAndRotateUserKeysRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.oldPassword, into: &buf)
        FfiConverterString.write(value.password, into: &buf)
        FfiConverterOptionString.write(value.hint, into: &buf)
        FfiConverterSequenceTypePublicKey.write(value.trustedEmergencyAccessPublicKeys, into: &buf)
        FfiConverterSequenceTypePublicKey.write(value.trustedOrganizationPublicKeys, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePasswordChangeAndRotateUserKeysRequest_lift(_ buf: RustBuffer) throws -> PasswordChangeAndRotateUserKeysRequest {
    return try FfiConverterTypePasswordChangeAndRotateUserKeysRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePasswordChangeAndRotateUserKeysRequest_lower(_ value: PasswordChangeAndRotateUserKeysRequest) -> RustBuffer {
    return FfiConverterTypePasswordChangeAndRotateUserKeysRequest.lower(value)
}


public struct RotateUserKeysRequest: Equatable, Hashable {
    public let keyRotationMethod: KeyRotationMethod
    public let trustedEmergencyAccessPublicKeys: [PublicKey]
    public let trustedOrganizationPublicKeys: [PublicKey]
    public let upgradeTokenAction: UpgradeTokenAction?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(keyRotationMethod: KeyRotationMethod, trustedEmergencyAccessPublicKeys: [PublicKey], trustedOrganizationPublicKeys: [PublicKey], upgradeTokenAction: UpgradeTokenAction?) {
        self.keyRotationMethod = keyRotationMethod
        self.trustedEmergencyAccessPublicKeys = trustedEmergencyAccessPublicKeys
        self.trustedOrganizationPublicKeys = trustedOrganizationPublicKeys
        self.upgradeTokenAction = upgradeTokenAction
    }

    

    
}

#if compiler(>=6)
extension RotateUserKeysRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRotateUserKeysRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RotateUserKeysRequest {
        return
            try RotateUserKeysRequest(
                keyRotationMethod: FfiConverterTypeKeyRotationMethod.read(from: &buf), 
                trustedEmergencyAccessPublicKeys: FfiConverterSequenceTypePublicKey.read(from: &buf), 
                trustedOrganizationPublicKeys: FfiConverterSequenceTypePublicKey.read(from: &buf), 
                upgradeTokenAction: FfiConverterOptionTypeUpgradeTokenAction.read(from: &buf)
        )
    }

    public static func write(_ value: RotateUserKeysRequest, into buf: inout [UInt8]) {
        FfiConverterTypeKeyRotationMethod.write(value.keyRotationMethod, into: &buf)
        FfiConverterSequenceTypePublicKey.write(value.trustedEmergencyAccessPublicKeys, into: &buf)
        FfiConverterSequenceTypePublicKey.write(value.trustedOrganizationPublicKeys, into: &buf)
        FfiConverterOptionTypeUpgradeTokenAction.write(value.upgradeTokenAction, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRotateUserKeysRequest_lift(_ buf: RustBuffer) throws -> RotateUserKeysRequest {
    return try FfiConverterTypeRotateUserKeysRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRotateUserKeysRequest_lower(_ value: RotateUserKeysRequest) -> RustBuffer {
    return FfiConverterTypeRotateUserKeysRequest.lower(value)
}


public enum KeyPairRegenerationError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case UserKeyNotAvailable(message: String)
    
    case Api(message: String)
    
    case Crypto(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension KeyPairRegenerationError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKeyPairRegenerationError: FfiConverterRustBuffer {
    typealias SwiftType = KeyPairRegenerationError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KeyPairRegenerationError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .UserKeyNotAvailable(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Api(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Crypto(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: KeyPairRegenerationError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .UserKeyNotAvailable(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Api(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Crypto(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyPairRegenerationError_lift(_ buf: RustBuffer) throws -> KeyPairRegenerationError {
    return try FfiConverterTypeKeyPairRegenerationError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyPairRegenerationError_lower(_ value: KeyPairRegenerationError) -> RustBuffer {
    return FfiConverterTypeKeyPairRegenerationError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum KeyRotationMethod: Equatable, Hashable {
    
    /**
     * Master password user, key rotation without a password change.
     */
    case password(password: String
    )
    /**
     * Key Connector user, key rotation without a password change.
     */
    case keyConnector(keyConnectorUrl: String
    )
    /**
     * TDE user, key rotation without a password change.
     * NOTE: This is not yet implemented and will return a
     * RotateUserKeysError::UnimplementedKeyRotationMethod error if used.
     */
    case tde





}

#if compiler(>=6)
extension KeyRotationMethod: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKeyRotationMethod: FfiConverterRustBuffer {
    typealias SwiftType = KeyRotationMethod

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KeyRotationMethod {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .password(password: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .keyConnector(keyConnectorUrl: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .tde
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: KeyRotationMethod, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .password(password):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(password, into: &buf)
            
        
        case let .keyConnector(keyConnectorUrl):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(keyConnectorUrl, into: &buf)
            
        
        case .tde:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyRotationMethod_lift(_ buf: RustBuffer) throws -> KeyRotationMethod {
    return try FfiConverterTypeKeyRotationMethod.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyRotationMethod_lower(_ value: KeyRotationMethod) -> RustBuffer {
    return FfiConverterTypeKeyRotationMethod.lower(value)
}



public enum MigrateToKeyConnectorError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case UserKeyNotAvailable(message: String)
    
    case Crypto(message: String)
    
    case Api(message: String)
    
    case KeyConnectorApi(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension MigrateToKeyConnectorError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMigrateToKeyConnectorError: FfiConverterRustBuffer {
    typealias SwiftType = MigrateToKeyConnectorError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MigrateToKeyConnectorError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .UserKeyNotAvailable(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Crypto(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Api(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .KeyConnectorApi(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MigrateToKeyConnectorError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .UserKeyNotAvailable(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Crypto(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Api(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .KeyConnectorApi(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMigrateToKeyConnectorError_lift(_ buf: RustBuffer) throws -> MigrateToKeyConnectorError {
    return try FfiConverterTypeMigrateToKeyConnectorError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMigrateToKeyConnectorError_lower(_ value: MigrateToKeyConnectorError) -> RustBuffer {
    return FfiConverterTypeMigrateToKeyConnectorError.lower(value)
}


/**
 * Errors returned by PIN settings operations.
 */
public enum PinSettingsError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * Failed while enrolling or storing the PIN-protected key envelope.
     */
    case SetPinState(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension PinSettingsError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePinSettingsError: FfiConverterRustBuffer {
    typealias SwiftType = PinSettingsError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PinSettingsError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .SetPinState(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PinSettingsError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .SetPinState(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePinSettingsError_lift(_ buf: RustBuffer) throws -> PinSettingsError {
    return try FfiConverterTypePinSettingsError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePinSettingsError_lower(_ value: PinSettingsError) -> RustBuffer {
    return FfiConverterTypePinSettingsError.lower(value)
}


public enum RotateUserKeysError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Api(message: String)
    
    case Crypto(message: String)
    
    case InvalidPublicKey(message: String)
    
    case KeyConnectorApi(message: String)
    
    case UntrustedKey(message: String)
    
    case UnimplementedKeyRotationMethod(message: String)
    
    case OldAttachments(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension RotateUserKeysError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRotateUserKeysError: FfiConverterRustBuffer {
    typealias SwiftType = RotateUserKeysError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RotateUserKeysError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Api(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Crypto(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .InvalidPublicKey(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .KeyConnectorApi(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .UntrustedKey(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .UnimplementedKeyRotationMethod(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .OldAttachments(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RotateUserKeysError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Api(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Crypto(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .InvalidPublicKey(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .KeyConnectorApi(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .UntrustedKey(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .UnimplementedKeyRotationMethod(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .OldAttachments(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRotateUserKeysError_lift(_ buf: RustBuffer) throws -> RotateUserKeysError {
    return try FfiConverterTypeRotateUserKeysError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRotateUserKeysError_lower(_ value: RotateUserKeysError) -> RustBuffer {
    return FfiConverterTypeRotateUserKeysError.lower(value)
}


public enum SyncError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Network(message: String)
    
    case Data(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SyncError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSyncError: FfiConverterRustBuffer {
    typealias SwiftType = SyncError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SyncError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Network(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Data(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SyncError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Network(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Data(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncError_lift(_ buf: RustBuffer) throws -> SyncError {
    return try FfiConverterTypeSyncError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncError_lower(_ value: SyncError) -> RustBuffer {
    return FfiConverterTypeSyncError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum UpgradeTokenAction: Equatable, Hashable {
    
    /**
     * Skip creating and sending an upgrade token to the server. This will be the default behavior
     * if the field is omitted.
     */
    case skip
    /**
     * Creates an upgrade token for V1 -> V2 key rotations.
     * For V2 -> V2 rotations, no upgrade token is needed.
     */
    case createIfNeeded





}

#if compiler(>=6)
extension UpgradeTokenAction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUpgradeTokenAction: FfiConverterRustBuffer {
    typealias SwiftType = UpgradeTokenAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UpgradeTokenAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .skip
        
        case 2: return .createIfNeeded
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: UpgradeTokenAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .skip:
            writeInt(&buf, Int32(1))
        
        
        case .createIfNeeded:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUpgradeTokenAction_lift(_ buf: RustBuffer) throws -> UpgradeTokenAction {
    return try FfiConverterTypeUpgradeTokenAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUpgradeTokenAction_lower(_ value: UpgradeTokenAction) -> RustBuffer {
    return FfiConverterTypeUpgradeTokenAction.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypePinLockType: FfiConverterRustBuffer {
    typealias SwiftType = PinLockType?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypePinLockType.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypePinLockType.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeUpgradeTokenAction: FfiConverterRustBuffer {
    typealias SwiftType = UpgradeTokenAction?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeUpgradeTokenAction.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeUpgradeTokenAction.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePublicKey: FfiConverterRustBuffer {
    typealias SwiftType = [PublicKey]

    public static func write(_ value: [PublicKey], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePublicKey.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PublicKey] {
        let len: Int32 = try readInt(&buf)
        var seq = [PublicKey]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePublicKey.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureBitwardenUserCryptoManagementInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_bitwarden_user_crypto_management_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_bitwarden_user_crypto_management_checksum_method_pinsettingsclient_get_lock_type() != 47108) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_user_crypto_management_checksum_method_pinsettingsclient_get_pin() != 40915) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_user_crypto_management_checksum_method_pinsettingsclient_get_status() != 13492) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_user_crypto_management_checksum_method_pinsettingsclient_set_pin() != 54964) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_user_crypto_management_checksum_method_pinsettingsclient_unset_pin() != 64665) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_user_crypto_management_checksum_method_pinsettingsclient_validate_pin() != 3295) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_user_crypto_management_checksum_method_usercryptomanagementclient_pin_settings() != 40704) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiEnsureBitwardenCoreInitialized()
    uniffiEnsureBitwardenCryptoInitialized()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureBitwardenUserCryptoManagementInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all