// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(BitwardenFFI)
import BitwardenFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_bitwarden_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_bitwarden_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
                throw CancellationError()

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}



public protocol ClientProtocol : AnyObject {
    func auth()  -> ClientAuth
    func crypto()  -> ClientCrypto
    func echo(msg: String)  -> String
    func generators()  -> ClientGenerators
    func vault()  -> ClientVault
    
}

public class Client: ClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }
    public convenience init(settings: ClientSettings?)  {
        self.init(unsafeFromRawPointer: try! rustCall() {
    uniffi_bitwarden_uniffi_fn_constructor_client_new(
        FfiConverterOptionTypeClientSettings.lower(settings),$0)
})
    }

    deinit {
        try! rustCall { uniffi_bitwarden_uniffi_fn_free_client(pointer, $0) }
    }

    

    
    

    public func auth()  -> ClientAuth {
        return try!  FfiConverterTypeClientAuth.lift(
            try! 
    rustCall() {
    
    uniffi_bitwarden_uniffi_fn_method_client_auth(self.pointer, $0
    )
}
        )
    }

    public func crypto()  -> ClientCrypto {
        return try!  FfiConverterTypeClientCrypto.lift(
            try! 
    rustCall() {
    
    uniffi_bitwarden_uniffi_fn_method_client_crypto(self.pointer, $0
    )
}
        )
    }

    public func echo(msg: String)  -> String {
        return try!  FfiConverterString.lift(
            try! 
    rustCall() {
    
    uniffi_bitwarden_uniffi_fn_method_client_echo(self.pointer, 
        FfiConverterString.lower(msg),$0
    )
}
        )
    }

    public func generators()  -> ClientGenerators {
        return try!  FfiConverterTypeClientGenerators.lift(
            try! 
    rustCall() {
    
    uniffi_bitwarden_uniffi_fn_method_client_generators(self.pointer, $0
    )
}
        )
    }

    public func vault()  -> ClientVault {
        return try!  FfiConverterTypeClientVault.lift(
            try! 
    rustCall() {
    
    uniffi_bitwarden_uniffi_fn_method_client_vault(self.pointer, $0
    )
}
        )
    }
}

public struct FfiConverterTypeClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Client

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Client {
        return Client(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Client) -> UnsafeMutableRawPointer {
        return value.pointer
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Client {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Client, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> Client {
    return try FfiConverterTypeClient.lift(pointer)
}

public func FfiConverterTypeClient_lower(_ value: Client) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClient.lower(value)
}



public protocol ClientAuthProtocol : AnyObject {
    func hashPassword(email: String, password: String, kdfParams: Kdf) async throws  -> String
    func makeRegisterKeys(email: String, password: String, kdf: Kdf) async throws  -> RegisterKeyResponse
    func passwordStrength(password: String, email: String, additionalInputs: [String]) async  -> UInt8
    func satisfiesPolicy(password: String, strength: UInt8, policy: MasterPasswordPolicyOptions) async  -> Bool
    
}

public class ClientAuth: ClientAuthProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_bitwarden_uniffi_fn_free_clientauth(pointer, $0) }
    }

    

    
    

    public func hashPassword(email: String, password: String, kdfParams: Kdf) async throws  -> String {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientauth_hash_password(
                    self.pointer,
                    FfiConverterString.lower(email),
                    FfiConverterString.lower(password),
                    FfiConverterTypeKdf_lower(kdfParams)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func makeRegisterKeys(email: String, password: String, kdf: Kdf) async throws  -> RegisterKeyResponse {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientauth_make_register_keys(
                    self.pointer,
                    FfiConverterString.lower(email),
                    FfiConverterString.lower(password),
                    FfiConverterTypeKdf_lower(kdf)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeRegisterKeyResponse_lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func passwordStrength(password: String, email: String, additionalInputs: [String]) async  -> UInt8 {
        return try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientauth_password_strength(
                    self.pointer,
                    FfiConverterString.lower(password),
                    FfiConverterString.lower(email),
                    FfiConverterSequenceString.lower(additionalInputs)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_u8,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_u8,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_u8,
            liftFunc: FfiConverterUInt8.lift,
            errorHandler: nil
            
        )
    }

    

    public func satisfiesPolicy(password: String, strength: UInt8, policy: MasterPasswordPolicyOptions) async  -> Bool {
        return try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientauth_satisfies_policy(
                    self.pointer,
                    FfiConverterString.lower(password),
                    FfiConverterUInt8.lower(strength),
                    FfiConverterTypeMasterPasswordPolicyOptions_lower(policy)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_i8,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_i8,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: nil
            
        )
    }

    
}

public struct FfiConverterTypeClientAuth: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClientAuth

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientAuth {
        return ClientAuth(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClientAuth) -> UnsafeMutableRawPointer {
        return value.pointer
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientAuth {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClientAuth, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeClientAuth_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientAuth {
    return try FfiConverterTypeClientAuth.lift(pointer)
}

public func FfiConverterTypeClientAuth_lower(_ value: ClientAuth) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClientAuth.lower(value)
}



public protocol ClientCiphersProtocol : AnyObject {
    func decrypt(cipher: Cipher) async throws  -> CipherView
    func decryptList(ciphers: [Cipher]) async throws  -> [CipherListView]
    func encrypt(cipherView: CipherView) async throws  -> Cipher
    
}

public class ClientCiphers: ClientCiphersProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_bitwarden_uniffi_fn_free_clientciphers(pointer, $0) }
    }

    

    
    

    public func decrypt(cipher: Cipher) async throws  -> CipherView {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientciphers_decrypt(
                    self.pointer,
                    FfiConverterTypeCipher_lower(cipher)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeCipherView_lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func decryptList(ciphers: [Cipher]) async throws  -> [CipherListView] {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientciphers_decrypt_list(
                    self.pointer,
                    FfiConverterSequenceTypeCipher.lower(ciphers)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeCipherListView.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func encrypt(cipherView: CipherView) async throws  -> Cipher {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientciphers_encrypt(
                    self.pointer,
                    FfiConverterTypeCipherView_lower(cipherView)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeCipher_lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    
}

public struct FfiConverterTypeClientCiphers: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClientCiphers

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientCiphers {
        return ClientCiphers(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClientCiphers) -> UnsafeMutableRawPointer {
        return value.pointer
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientCiphers {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClientCiphers, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeClientCiphers_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientCiphers {
    return try FfiConverterTypeClientCiphers.lift(pointer)
}

public func FfiConverterTypeClientCiphers_lower(_ value: ClientCiphers) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClientCiphers.lower(value)
}



public protocol ClientCollectionsProtocol : AnyObject {
    func decrypt(collection: Collection) async throws  -> CollectionView
    func decryptList(collections: [Collection]) async throws  -> [CollectionView]
    
}

public class ClientCollections: ClientCollectionsProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_bitwarden_uniffi_fn_free_clientcollections(pointer, $0) }
    }

    

    
    

    public func decrypt(collection: Collection) async throws  -> CollectionView {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientcollections_decrypt(
                    self.pointer,
                    FfiConverterTypeCollection_lower(collection)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeCollectionView_lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func decryptList(collections: [Collection]) async throws  -> [CollectionView] {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientcollections_decrypt_list(
                    self.pointer,
                    FfiConverterSequenceTypeCollection.lower(collections)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeCollectionView.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    
}

public struct FfiConverterTypeClientCollections: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClientCollections

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientCollections {
        return ClientCollections(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClientCollections) -> UnsafeMutableRawPointer {
        return value.pointer
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientCollections {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClientCollections, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeClientCollections_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientCollections {
    return try FfiConverterTypeClientCollections.lift(pointer)
}

public func FfiConverterTypeClientCollections_lower(_ value: ClientCollections) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClientCollections.lower(value)
}



public protocol ClientCryptoProtocol : AnyObject {
    func initializeCrypto(req: InitCryptoRequest) async throws 
    
}

public class ClientCrypto: ClientCryptoProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_bitwarden_uniffi_fn_free_clientcrypto(pointer, $0) }
    }

    

    
    

    public func initializeCrypto(req: InitCryptoRequest) async throws  {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientcrypto_initialize_crypto(
                    self.pointer,
                    FfiConverterTypeInitCryptoRequest_lower(req)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_void,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_void,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    
}

public struct FfiConverterTypeClientCrypto: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClientCrypto

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientCrypto {
        return ClientCrypto(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClientCrypto) -> UnsafeMutableRawPointer {
        return value.pointer
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientCrypto {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClientCrypto, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeClientCrypto_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientCrypto {
    return try FfiConverterTypeClientCrypto.lift(pointer)
}

public func FfiConverterTypeClientCrypto_lower(_ value: ClientCrypto) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClientCrypto.lower(value)
}



public protocol ClientExportersProtocol : AnyObject {
    func exportOrganizationVault(collections: [Collection], ciphers: [Cipher], format: ExportFormat) async throws  -> String
    func exportVault(folders: [Folder], ciphers: [Cipher], format: ExportFormat) async throws  -> String
    
}

public class ClientExporters: ClientExportersProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_bitwarden_uniffi_fn_free_clientexporters(pointer, $0) }
    }

    

    
    

    public func exportOrganizationVault(collections: [Collection], ciphers: [Cipher], format: ExportFormat) async throws  -> String {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientexporters_export_organization_vault(
                    self.pointer,
                    FfiConverterSequenceTypeCollection.lower(collections),
                    FfiConverterSequenceTypeCipher.lower(ciphers),
                    FfiConverterTypeExportFormat_lower(format)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func exportVault(folders: [Folder], ciphers: [Cipher], format: ExportFormat) async throws  -> String {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientexporters_export_vault(
                    self.pointer,
                    FfiConverterSequenceTypeFolder.lower(folders),
                    FfiConverterSequenceTypeCipher.lower(ciphers),
                    FfiConverterTypeExportFormat_lower(format)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    
}

public struct FfiConverterTypeClientExporters: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClientExporters

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientExporters {
        return ClientExporters(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClientExporters) -> UnsafeMutableRawPointer {
        return value.pointer
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientExporters {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClientExporters, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeClientExporters_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientExporters {
    return try FfiConverterTypeClientExporters.lift(pointer)
}

public func FfiConverterTypeClientExporters_lower(_ value: ClientExporters) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClientExporters.lower(value)
}



public protocol ClientFoldersProtocol : AnyObject {
    func decrypt(folder: Folder) async throws  -> FolderView
    func decryptList(folders: [Folder]) async throws  -> [FolderView]
    func encrypt(folder: FolderView) async throws  -> Folder
    
}

public class ClientFolders: ClientFoldersProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_bitwarden_uniffi_fn_free_clientfolders(pointer, $0) }
    }

    

    
    

    public func decrypt(folder: Folder) async throws  -> FolderView {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientfolders_decrypt(
                    self.pointer,
                    FfiConverterTypeFolder_lower(folder)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFolderView_lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func decryptList(folders: [Folder]) async throws  -> [FolderView] {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientfolders_decrypt_list(
                    self.pointer,
                    FfiConverterSequenceTypeFolder.lower(folders)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFolderView.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func encrypt(folder: FolderView) async throws  -> Folder {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientfolders_encrypt(
                    self.pointer,
                    FfiConverterTypeFolderView_lower(folder)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFolder_lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    
}

public struct FfiConverterTypeClientFolders: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClientFolders

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientFolders {
        return ClientFolders(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClientFolders) -> UnsafeMutableRawPointer {
        return value.pointer
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientFolders {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClientFolders, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeClientFolders_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientFolders {
    return try FfiConverterTypeClientFolders.lift(pointer)
}

public func FfiConverterTypeClientFolders_lower(_ value: ClientFolders) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClientFolders.lower(value)
}



public protocol ClientGeneratorsProtocol : AnyObject {
    func passphrase(settings: PassphraseGeneratorRequest) async throws  -> String
    func password(settings: PasswordGeneratorRequest) async throws  -> String
    
}

public class ClientGenerators: ClientGeneratorsProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_bitwarden_uniffi_fn_free_clientgenerators(pointer, $0) }
    }

    

    
    

    public func passphrase(settings: PassphraseGeneratorRequest) async throws  -> String {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientgenerators_passphrase(
                    self.pointer,
                    FfiConverterTypePassphraseGeneratorRequest_lower(settings)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func password(settings: PasswordGeneratorRequest) async throws  -> String {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientgenerators_password(
                    self.pointer,
                    FfiConverterTypePasswordGeneratorRequest_lower(settings)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    
}

public struct FfiConverterTypeClientGenerators: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClientGenerators

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientGenerators {
        return ClientGenerators(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClientGenerators) -> UnsafeMutableRawPointer {
        return value.pointer
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientGenerators {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClientGenerators, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeClientGenerators_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientGenerators {
    return try FfiConverterTypeClientGenerators.lift(pointer)
}

public func FfiConverterTypeClientGenerators_lower(_ value: ClientGenerators) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClientGenerators.lower(value)
}



public protocol ClientPasswordHistoryProtocol : AnyObject {
    func decryptList(list: [PasswordHistory]) async throws  -> [PasswordHistoryView]
    func encrypt(passwordHistory: PasswordHistoryView) async throws  -> PasswordHistory
    
}

public class ClientPasswordHistory: ClientPasswordHistoryProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_bitwarden_uniffi_fn_free_clientpasswordhistory(pointer, $0) }
    }

    

    
    

    public func decryptList(list: [PasswordHistory]) async throws  -> [PasswordHistoryView] {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientpasswordhistory_decrypt_list(
                    self.pointer,
                    FfiConverterSequenceTypePasswordHistory.lower(list)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypePasswordHistoryView.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func encrypt(passwordHistory: PasswordHistoryView) async throws  -> PasswordHistory {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientpasswordhistory_encrypt(
                    self.pointer,
                    FfiConverterTypePasswordHistoryView_lower(passwordHistory)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypePasswordHistory_lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    
}

public struct FfiConverterTypeClientPasswordHistory: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClientPasswordHistory

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientPasswordHistory {
        return ClientPasswordHistory(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClientPasswordHistory) -> UnsafeMutableRawPointer {
        return value.pointer
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientPasswordHistory {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClientPasswordHistory, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeClientPasswordHistory_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientPasswordHistory {
    return try FfiConverterTypeClientPasswordHistory.lift(pointer)
}

public func FfiConverterTypeClientPasswordHistory_lower(_ value: ClientPasswordHistory) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClientPasswordHistory.lower(value)
}



public protocol ClientSendsProtocol : AnyObject {
    func decrypt(send: Send) async throws  -> SendView
    func decryptBuffer(send: Send, buffer: Data) async throws  -> Data
    func decryptFile(send: Send, encryptedFilePath: String, decryptedFilePath: String) async throws 
    func decryptList(sends: [Send]) async throws  -> [SendListView]
    func encrypt(send: SendView) async throws  -> Send
    func encryptBuffer(send: Send, buffer: Data) async throws  -> Data
    func encryptFile(send: Send, decryptedFilePath: String, encryptedFilePath: String) async throws 
    
}

public class ClientSends: ClientSendsProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_bitwarden_uniffi_fn_free_clientsends(pointer, $0) }
    }

    

    
    

    public func decrypt(send: Send) async throws  -> SendView {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientsends_decrypt(
                    self.pointer,
                    FfiConverterTypeSend_lower(send)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSendView_lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func decryptBuffer(send: Send, buffer: Data) async throws  -> Data {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientsends_decrypt_buffer(
                    self.pointer,
                    FfiConverterTypeSend_lower(send),
                    FfiConverterData.lower(buffer)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func decryptFile(send: Send, encryptedFilePath: String, decryptedFilePath: String) async throws  {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientsends_decrypt_file(
                    self.pointer,
                    FfiConverterTypeSend_lower(send),
                    FfiConverterString.lower(encryptedFilePath),
                    FfiConverterString.lower(decryptedFilePath)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_void,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_void,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func decryptList(sends: [Send]) async throws  -> [SendListView] {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientsends_decrypt_list(
                    self.pointer,
                    FfiConverterSequenceTypeSend.lower(sends)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeSendListView.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func encrypt(send: SendView) async throws  -> Send {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientsends_encrypt(
                    self.pointer,
                    FfiConverterTypeSendView_lower(send)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSend_lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func encryptBuffer(send: Send, buffer: Data) async throws  -> Data {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientsends_encrypt_buffer(
                    self.pointer,
                    FfiConverterTypeSend_lower(send),
                    FfiConverterData.lower(buffer)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    

    public func encryptFile(send: Send, decryptedFilePath: String, encryptedFilePath: String) async throws  {
        return try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientsends_encrypt_file(
                    self.pointer,
                    FfiConverterTypeSend_lower(send),
                    FfiConverterString.lower(decryptedFilePath),
                    FfiConverterString.lower(encryptedFilePath)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_void,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_void,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeBitwardenError.lift
        )
    }

    
}

public struct FfiConverterTypeClientSends: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClientSends

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientSends {
        return ClientSends(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClientSends) -> UnsafeMutableRawPointer {
        return value.pointer
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientSends {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClientSends, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeClientSends_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientSends {
    return try FfiConverterTypeClientSends.lift(pointer)
}

public func FfiConverterTypeClientSends_lower(_ value: ClientSends) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClientSends.lower(value)
}



public protocol ClientVaultProtocol : AnyObject {
    func ciphers()  -> ClientCiphers
    func collections()  -> ClientCollections
    func folders()  -> ClientFolders
    func generateTotp(key: String, time: DateTime?) async  -> TotpResponse
    func passwordHistory()  -> ClientPasswordHistory
    func sends()  -> ClientSends
    
}

public class ClientVault: ClientVaultProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_bitwarden_uniffi_fn_free_clientvault(pointer, $0) }
    }

    

    
    

    public func ciphers()  -> ClientCiphers {
        return try!  FfiConverterTypeClientCiphers.lift(
            try! 
    rustCall() {
    
    uniffi_bitwarden_uniffi_fn_method_clientvault_ciphers(self.pointer, $0
    )
}
        )
    }

    public func collections()  -> ClientCollections {
        return try!  FfiConverterTypeClientCollections.lift(
            try! 
    rustCall() {
    
    uniffi_bitwarden_uniffi_fn_method_clientvault_collections(self.pointer, $0
    )
}
        )
    }

    public func folders()  -> ClientFolders {
        return try!  FfiConverterTypeClientFolders.lift(
            try! 
    rustCall() {
    
    uniffi_bitwarden_uniffi_fn_method_clientvault_folders(self.pointer, $0
    )
}
        )
    }

    public func generateTotp(key: String, time: DateTime?) async  -> TotpResponse {
        return try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_bitwarden_uniffi_fn_method_clientvault_generate_totp(
                    self.pointer,
                    FfiConverterString.lower(key),
                    FfiConverterOptionTypeDateTime.lower(time)
                )
            },
            pollFunc: ffi_bitwarden_uniffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_bitwarden_uniffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_bitwarden_uniffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeTotpResponse_lift,
            errorHandler: nil
            
        )
    }

    

    public func passwordHistory()  -> ClientPasswordHistory {
        return try!  FfiConverterTypeClientPasswordHistory.lift(
            try! 
    rustCall() {
    
    uniffi_bitwarden_uniffi_fn_method_clientvault_password_history(self.pointer, $0
    )
}
        )
    }

    public func sends()  -> ClientSends {
        return try!  FfiConverterTypeClientSends.lift(
            try! 
    rustCall() {
    
    uniffi_bitwarden_uniffi_fn_method_clientvault_sends(self.pointer, $0
    )
}
        )
    }
}

public struct FfiConverterTypeClientVault: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClientVault

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientVault {
        return ClientVault(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClientVault) -> UnsafeMutableRawPointer {
        return value.pointer
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientVault {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClientVault, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeClientVault_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClientVault {
    return try FfiConverterTypeClientVault.lift(pointer)
}

public func FfiConverterTypeClientVault_lower(_ value: ClientVault) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClientVault.lower(value)
}

public enum BitwardenError {

    
    
    // Simple error enums only carry a message
    case E(message: String)
    

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeBitwardenError.lift(error)
    }
}


public struct FfiConverterTypeBitwardenError: FfiConverterRustBuffer {
    typealias SwiftType = BitwardenError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BitwardenError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .E(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BitwardenError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .E(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))

        
        }
    }
}


extension BitwardenError: Equatable, Hashable {}

extension BitwardenError: Error { }

fileprivate struct FfiConverterOptionTypeClientSettings: FfiConverterRustBuffer {
    typealias SwiftType = ClientSettings?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeClientSettings.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeClientSettings.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionTypeDateTime: FfiConverterRustBuffer {
    typealias SwiftType = DateTime?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDateTime.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDateTime.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeCipher: FfiConverterRustBuffer {
    typealias SwiftType = [Cipher]

    public static func write(_ value: [Cipher], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCipher.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Cipher] {
        let len: Int32 = try readInt(&buf)
        var seq = [Cipher]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCipher.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeCipherListView: FfiConverterRustBuffer {
    typealias SwiftType = [CipherListView]

    public static func write(_ value: [CipherListView], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCipherListView.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CipherListView] {
        let len: Int32 = try readInt(&buf)
        var seq = [CipherListView]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCipherListView.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeCollection: FfiConverterRustBuffer {
    typealias SwiftType = [Collection]

    public static func write(_ value: [Collection], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCollection.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Collection] {
        let len: Int32 = try readInt(&buf)
        var seq = [Collection]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCollection.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeCollectionView: FfiConverterRustBuffer {
    typealias SwiftType = [CollectionView]

    public static func write(_ value: [CollectionView], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCollectionView.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CollectionView] {
        let len: Int32 = try readInt(&buf)
        var seq = [CollectionView]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCollectionView.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeFolder: FfiConverterRustBuffer {
    typealias SwiftType = [Folder]

    public static func write(_ value: [Folder], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFolder.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Folder] {
        let len: Int32 = try readInt(&buf)
        var seq = [Folder]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFolder.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeFolderView: FfiConverterRustBuffer {
    typealias SwiftType = [FolderView]

    public static func write(_ value: [FolderView], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFolderView.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FolderView] {
        let len: Int32 = try readInt(&buf)
        var seq = [FolderView]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFolderView.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypePasswordHistory: FfiConverterRustBuffer {
    typealias SwiftType = [PasswordHistory]

    public static func write(_ value: [PasswordHistory], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePasswordHistory.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PasswordHistory] {
        let len: Int32 = try readInt(&buf)
        var seq = [PasswordHistory]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePasswordHistory.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypePasswordHistoryView: FfiConverterRustBuffer {
    typealias SwiftType = [PasswordHistoryView]

    public static func write(_ value: [PasswordHistoryView], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePasswordHistoryView.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PasswordHistoryView] {
        let len: Int32 = try readInt(&buf)
        var seq = [PasswordHistoryView]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePasswordHistoryView.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeSend: FfiConverterRustBuffer {
    typealias SwiftType = [Send]

    public static func write(_ value: [Send], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSend.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Send] {
        let len: Int32 = try readInt(&buf)
        var seq = [Send]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSend.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeSendListView: FfiConverterRustBuffer {
    typealias SwiftType = [SendListView]

    public static func write(_ value: [SendListView], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSendListView.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SendListView] {
        let len: Int32 = try readInt(&buf)
        var seq = [SendListView]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSendListView.read(from: &buf))
        }
        return seq
    }
}












































private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UnsafeMutableRawPointer,
    pollFunc: (UnsafeMutableRawPointer, @escaping UniFfiRustFutureContinuation, UnsafeMutableRawPointer) -> (),
    completeFunc: (UnsafeMutableRawPointer, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UnsafeMutableRawPointer) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) async throws -> T {
    // Make sure to call uniffiEnsureInitialized() since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(rustFuture, uniffiFutureContinuationCallback, ContinuationHolder($0).toOpaque())
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(ptr: UnsafeMutableRawPointer, pollResult: Int8) {
    ContinuationHolder.fromOpaque(ptr).resume(pollResult)
}

// Wraps UnsafeContinuation in a class so that we can use reference counting when passing it across
// the FFI
fileprivate class ContinuationHolder {
    let continuation: UnsafeContinuation<Int8, Never>

    init(_ continuation: UnsafeContinuation<Int8, Never>) {
        self.continuation = continuation
    }

    func resume(_ pollResult: Int8) {
        self.continuation.resume(returning: pollResult)
    }

    func toOpaque() -> UnsafeMutableRawPointer {
        return Unmanaged<ContinuationHolder>.passRetained(self).toOpaque()
    }

    static func fromOpaque(_ ptr: UnsafeRawPointer) -> ContinuationHolder {
        return Unmanaged<ContinuationHolder>.fromOpaque(ptr).takeRetainedValue()
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 25
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_bitwarden_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_client_auth() != 9299) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_client_crypto() != 50097) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_client_echo() != 17135) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_client_generators() != 54338) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_client_vault() != 62276) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientauth_hash_password() != 11695) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientauth_make_register_keys() != 49256) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientauth_password_strength() != 5352) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientauth_satisfies_policy() != 38024) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientciphers_decrypt() != 54536) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientciphers_decrypt_list() != 51333) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientciphers_encrypt() != 2060) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientcollections_decrypt() != 2515) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientcollections_decrypt_list() != 54660) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientcrypto_initialize_crypto() != 45104) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientexporters_export_organization_vault() != 4952) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientexporters_export_vault() != 11990) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientfolders_decrypt() != 1351) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientfolders_decrypt_list() != 37050) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientfolders_encrypt() != 54957) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientgenerators_passphrase() != 14402) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientgenerators_password() != 3370) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientpasswordhistory_decrypt_list() != 19686) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientpasswordhistory_encrypt() != 38769) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientsends_decrypt() != 12489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientsends_decrypt_buffer() != 19741) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientsends_decrypt_file() != 8851) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientsends_decrypt_list() != 3693) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientsends_encrypt() != 6399) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientsends_encrypt_buffer() != 19766) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientsends_encrypt_file() != 11305) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientvault_ciphers() != 31213) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientvault_collections() != 49218) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientvault_folders() != 18540) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientvault_generate_totp() != 32001) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientvault_password_history() != 10182) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_method_clientvault_sends() != 17906) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bitwarden_uniffi_checksum_constructor_client_new() != 21800) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}