// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(BitwardenSendFFI)
import BitwardenSendFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_bitwarden_send_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_bitwarden_send_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureBitwardenSendInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterTimestamp: FfiConverterRustBuffer {
    typealias SwiftType = Date

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Date {
        let seconds: Int64 = try readInt(&buf)
        let nanoseconds: UInt32 = try readInt(&buf)
        if seconds >= 0 {
            let delta = Double(seconds) + (Double(nanoseconds) / 1.0e9)
            return Date.init(timeIntervalSince1970: delta)
        } else {
            let delta = Double(seconds) - (Double(nanoseconds) / 1.0e9)
            return Date.init(timeIntervalSince1970: delta)
        }
    }

    public static func write(_ value: Date, into buf: inout [UInt8]) {
        var delta = value.timeIntervalSince1970
        var sign: Int64 = 1
        if delta < 0 {
            // The nanoseconds portion of the epoch offset must always be
            // positive, to simplify the calculation we will use the absolute
            // value of the offset.
            sign = -1
            delta = -delta
        }
        if delta.rounded(.down) > Double(Int64.max) {
            fatalError("Timestamp overflow, exceeds max bounds supported by Uniffi")
        }
        let seconds = Int64(delta)
        let nanoseconds = UInt32((delta - Double(seconds)) * 1.0e9)
        writeInt(&buf, sign * seconds)
        writeInt(&buf, nanoseconds)
    }
}


public struct Send: Equatable, Hashable {
    public let id: SendId?
    public let accessId: String?
    public let name: EncString
    public let notes: EncString?
    public let key: EncString
    public let password: String?
    public let type: SendType
    public let file: SendFile?
    public let text: SendText?
    public let maxAccessCount: UInt32?
    public let accessCount: UInt32
    public let disabled: Bool
    public let hideEmail: Bool
    public let revisionDate: DateTime
    public let deletionDate: DateTime
    public let expirationDate: DateTime?
    /**
     * Email addresses for OTP authentication (comma-separated).
     *
     * **Note**: Mutually exclusive with `password`. If both `password` and `emails` are
     * set, password authentication takes precedence and email OTP is ignored.
     */
    public let emails: String?
    public let authType: AuthType

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: SendId?, accessId: String?, name: EncString, notes: EncString?, key: EncString, password: String?, type: SendType, file: SendFile?, text: SendText?, maxAccessCount: UInt32?, accessCount: UInt32, disabled: Bool, hideEmail: Bool, revisionDate: DateTime, deletionDate: DateTime, expirationDate: DateTime?, 
        /**
         * Email addresses for OTP authentication (comma-separated).
         *
         * **Note**: Mutually exclusive with `password`. If both `password` and `emails` are
         * set, password authentication takes precedence and email OTP is ignored.
         */emails: String?, authType: AuthType) {
        self.id = id
        self.accessId = accessId
        self.name = name
        self.notes = notes
        self.key = key
        self.password = password
        self.type = type
        self.file = file
        self.text = text
        self.maxAccessCount = maxAccessCount
        self.accessCount = accessCount
        self.disabled = disabled
        self.hideEmail = hideEmail
        self.revisionDate = revisionDate
        self.deletionDate = deletionDate
        self.expirationDate = expirationDate
        self.emails = emails
        self.authType = authType
    }

    

    
}

#if compiler(>=6)
extension Send: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSend: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Send {
        return
            try Send(
                id: FfiConverterOptionTypeSendId.read(from: &buf), 
                accessId: FfiConverterOptionString.read(from: &buf), 
                name: FfiConverterTypeEncString.read(from: &buf), 
                notes: FfiConverterOptionTypeEncString.read(from: &buf), 
                key: FfiConverterTypeEncString.read(from: &buf), 
                password: FfiConverterOptionString.read(from: &buf), 
                type: FfiConverterTypeSendType.read(from: &buf), 
                file: FfiConverterOptionTypeSendFile.read(from: &buf), 
                text: FfiConverterOptionTypeSendText.read(from: &buf), 
                maxAccessCount: FfiConverterOptionUInt32.read(from: &buf), 
                accessCount: FfiConverterUInt32.read(from: &buf), 
                disabled: FfiConverterBool.read(from: &buf), 
                hideEmail: FfiConverterBool.read(from: &buf), 
                revisionDate: FfiConverterTypeDateTime.read(from: &buf), 
                deletionDate: FfiConverterTypeDateTime.read(from: &buf), 
                expirationDate: FfiConverterOptionTypeDateTime.read(from: &buf), 
                emails: FfiConverterOptionString.read(from: &buf), 
                authType: FfiConverterTypeAuthType.read(from: &buf)
        )
    }

    public static func write(_ value: Send, into buf: inout [UInt8]) {
        FfiConverterOptionTypeSendId.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.accessId, into: &buf)
        FfiConverterTypeEncString.write(value.name, into: &buf)
        FfiConverterOptionTypeEncString.write(value.notes, into: &buf)
        FfiConverterTypeEncString.write(value.key, into: &buf)
        FfiConverterOptionString.write(value.password, into: &buf)
        FfiConverterTypeSendType.write(value.type, into: &buf)
        FfiConverterOptionTypeSendFile.write(value.file, into: &buf)
        FfiConverterOptionTypeSendText.write(value.text, into: &buf)
        FfiConverterOptionUInt32.write(value.maxAccessCount, into: &buf)
        FfiConverterUInt32.write(value.accessCount, into: &buf)
        FfiConverterBool.write(value.disabled, into: &buf)
        FfiConverterBool.write(value.hideEmail, into: &buf)
        FfiConverterTypeDateTime.write(value.revisionDate, into: &buf)
        FfiConverterTypeDateTime.write(value.deletionDate, into: &buf)
        FfiConverterOptionTypeDateTime.write(value.expirationDate, into: &buf)
        FfiConverterOptionString.write(value.emails, into: &buf)
        FfiConverterTypeAuthType.write(value.authType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSend_lift(_ buf: RustBuffer) throws -> Send {
    return try FfiConverterTypeSend.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSend_lower(_ value: Send) -> RustBuffer {
    return FfiConverterTypeSend.lower(value)
}


/**
 * File-based send content
 */
public struct SendFile: Equatable, Hashable {
    /**
     * The file's ID
     */
    public let id: String?
    /**
     * The encrypted file name
     */
    public let fileName: EncString
    /**
     * The file size in bytes as a string
     */
    public let size: String?
    /**
     * Readable size, ex: "4.2 KB" or "1.43 GB"
     */
    public let sizeName: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The file's ID
         */id: String?, 
        /**
         * The encrypted file name
         */fileName: EncString, 
        /**
         * The file size in bytes as a string
         */size: String?, 
        /**
         * Readable size, ex: "4.2 KB" or "1.43 GB"
         */sizeName: String?) {
        self.id = id
        self.fileName = fileName
        self.size = size
        self.sizeName = sizeName
    }

    

    
}

#if compiler(>=6)
extension SendFile: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendFile: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendFile {
        return
            try SendFile(
                id: FfiConverterOptionString.read(from: &buf), 
                fileName: FfiConverterTypeEncString.read(from: &buf), 
                size: FfiConverterOptionString.read(from: &buf), 
                sizeName: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SendFile, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.id, into: &buf)
        FfiConverterTypeEncString.write(value.fileName, into: &buf)
        FfiConverterOptionString.write(value.size, into: &buf)
        FfiConverterOptionString.write(value.sizeName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendFile_lift(_ buf: RustBuffer) throws -> SendFile {
    return try FfiConverterTypeSendFile.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendFile_lower(_ value: SendFile) -> RustBuffer {
    return FfiConverterTypeSendFile.lower(value)
}


/**
 * View model for decrypted SendFile
 */
public struct SendFileView: Equatable, Hashable {
    /**
     * The file's ID
     */
    public let id: String?
    /**
     * The file name
     */
    public let fileName: String
    /**
     * The file size in bytes as a string
     */
    public let size: String?
    /**
     * Readable size, ex: "4.2 KB" or "1.43 GB"
     */
    public let sizeName: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The file's ID
         */id: String?, 
        /**
         * The file name
         */fileName: String, 
        /**
         * The file size in bytes as a string
         */size: String?, 
        /**
         * Readable size, ex: "4.2 KB" or "1.43 GB"
         */sizeName: String?) {
        self.id = id
        self.fileName = fileName
        self.size = size
        self.sizeName = sizeName
    }

    

    
}

#if compiler(>=6)
extension SendFileView: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendFileView: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendFileView {
        return
            try SendFileView(
                id: FfiConverterOptionString.read(from: &buf), 
                fileName: FfiConverterString.read(from: &buf), 
                size: FfiConverterOptionString.read(from: &buf), 
                sizeName: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SendFileView, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.id, into: &buf)
        FfiConverterString.write(value.fileName, into: &buf)
        FfiConverterOptionString.write(value.size, into: &buf)
        FfiConverterOptionString.write(value.sizeName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendFileView_lift(_ buf: RustBuffer) throws -> SendFileView {
    return try FfiConverterTypeSendFileView.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendFileView_lower(_ value: SendFileView) -> RustBuffer {
    return FfiConverterTypeSendFileView.lower(value)
}


public struct SendListView: Equatable, Hashable {
    public let id: SendId?
    public let accessId: String?
    public let name: String
    public let type: SendType
    public let disabled: Bool
    public let revisionDate: DateTime
    public let deletionDate: DateTime
    public let expirationDate: DateTime?
    public let authType: AuthType

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: SendId?, accessId: String?, name: String, type: SendType, disabled: Bool, revisionDate: DateTime, deletionDate: DateTime, expirationDate: DateTime?, authType: AuthType) {
        self.id = id
        self.accessId = accessId
        self.name = name
        self.type = type
        self.disabled = disabled
        self.revisionDate = revisionDate
        self.deletionDate = deletionDate
        self.expirationDate = expirationDate
        self.authType = authType
    }

    

    
}

#if compiler(>=6)
extension SendListView: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendListView: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendListView {
        return
            try SendListView(
                id: FfiConverterOptionTypeSendId.read(from: &buf), 
                accessId: FfiConverterOptionString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                type: FfiConverterTypeSendType.read(from: &buf), 
                disabled: FfiConverterBool.read(from: &buf), 
                revisionDate: FfiConverterTypeDateTime.read(from: &buf), 
                deletionDate: FfiConverterTypeDateTime.read(from: &buf), 
                expirationDate: FfiConverterOptionTypeDateTime.read(from: &buf), 
                authType: FfiConverterTypeAuthType.read(from: &buf)
        )
    }

    public static func write(_ value: SendListView, into buf: inout [UInt8]) {
        FfiConverterOptionTypeSendId.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.accessId, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterTypeSendType.write(value.type, into: &buf)
        FfiConverterBool.write(value.disabled, into: &buf)
        FfiConverterTypeDateTime.write(value.revisionDate, into: &buf)
        FfiConverterTypeDateTime.write(value.deletionDate, into: &buf)
        FfiConverterOptionTypeDateTime.write(value.expirationDate, into: &buf)
        FfiConverterTypeAuthType.write(value.authType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendListView_lift(_ buf: RustBuffer) throws -> SendListView {
    return try FfiConverterTypeSendListView.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendListView_lower(_ value: SendListView) -> RustBuffer {
    return FfiConverterTypeSendListView.lower(value)
}


/**
 * Text-based send content
 */
public struct SendText: Equatable, Hashable {
    public let text: EncString?
    public let hidden: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(text: EncString?, hidden: Bool) {
        self.text = text
        self.hidden = hidden
    }

    

    
}

#if compiler(>=6)
extension SendText: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendText: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendText {
        return
            try SendText(
                text: FfiConverterOptionTypeEncString.read(from: &buf), 
                hidden: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: SendText, into buf: inout [UInt8]) {
        FfiConverterOptionTypeEncString.write(value.text, into: &buf)
        FfiConverterBool.write(value.hidden, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendText_lift(_ buf: RustBuffer) throws -> SendText {
    return try FfiConverterTypeSendText.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendText_lower(_ value: SendText) -> RustBuffer {
    return FfiConverterTypeSendText.lower(value)
}


/**
 * View model for decrypted SendText
 */
public struct SendTextView: Equatable, Hashable {
    /**
     * The text content of the send
     */
    public let text: String?
    /**
     * Whether the text is hidden-by-default (masked as ********).
     */
    public let hidden: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The text content of the send
         */text: String?, 
        /**
         * Whether the text is hidden-by-default (masked as ********).
         */hidden: Bool) {
        self.text = text
        self.hidden = hidden
    }

    

    
}

#if compiler(>=6)
extension SendTextView: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendTextView: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendTextView {
        return
            try SendTextView(
                text: FfiConverterOptionString.read(from: &buf), 
                hidden: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: SendTextView, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.text, into: &buf)
        FfiConverterBool.write(value.hidden, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendTextView_lift(_ buf: RustBuffer) throws -> SendTextView {
    return try FfiConverterTypeSendTextView.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendTextView_lower(_ value: SendTextView) -> RustBuffer {
    return FfiConverterTypeSendTextView.lower(value)
}


public struct SendView: Equatable, Hashable {
    public let id: SendId?
    public let accessId: String?
    public let name: String
    public let notes: String?
    /**
     * Base64 encoded key
     */
    public let key: String?
    /**
     * Replace or add a password to an existing send. The SDK will always return None when
     * decrypting a [Send]
     * TODO: We should revisit this, one variant is to have `[Create, Update]SendView` DTOs.
     */
    public let newPassword: String?
    /**
     * Denote if an existing send has a password. The SDK will ignore this value when creating or
     * updating sends.
     */
    public let hasPassword: Bool
    public let type: SendType
    public let file: SendFileView?
    public let text: SendTextView?
    public let maxAccessCount: UInt32?
    public let accessCount: UInt32
    public let disabled: Bool
    public let hideEmail: Bool
    public let revisionDate: DateTime
    public let deletionDate: DateTime
    public let expirationDate: DateTime?
    /**
     * Email addresses for OTP authentication.
     * **Note**: Mutually exclusive with `new_password`. If both are set, only password
     * authentication will be used. When creating or editing sends, use [crate::SendAuthType]
     * to ensure mutual exclusivity at the type level.
     */
    public let emails: [String]
    public let authType: AuthType

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: SendId?, accessId: String?, name: String, notes: String?, 
        /**
         * Base64 encoded key
         */key: String?, 
        /**
         * Replace or add a password to an existing send. The SDK will always return None when
         * decrypting a [Send]
         * TODO: We should revisit this, one variant is to have `[Create, Update]SendView` DTOs.
         */newPassword: String?, 
        /**
         * Denote if an existing send has a password. The SDK will ignore this value when creating or
         * updating sends.
         */hasPassword: Bool, type: SendType, file: SendFileView?, text: SendTextView?, maxAccessCount: UInt32?, accessCount: UInt32, disabled: Bool, hideEmail: Bool, revisionDate: DateTime, deletionDate: DateTime, expirationDate: DateTime?, 
        /**
         * Email addresses for OTP authentication.
         * **Note**: Mutually exclusive with `new_password`. If both are set, only password
         * authentication will be used. When creating or editing sends, use [crate::SendAuthType]
         * to ensure mutual exclusivity at the type level.
         */emails: [String], authType: AuthType) {
        self.id = id
        self.accessId = accessId
        self.name = name
        self.notes = notes
        self.key = key
        self.newPassword = newPassword
        self.hasPassword = hasPassword
        self.type = type
        self.file = file
        self.text = text
        self.maxAccessCount = maxAccessCount
        self.accessCount = accessCount
        self.disabled = disabled
        self.hideEmail = hideEmail
        self.revisionDate = revisionDate
        self.deletionDate = deletionDate
        self.expirationDate = expirationDate
        self.emails = emails
        self.authType = authType
    }

    

    
}

#if compiler(>=6)
extension SendView: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendView: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendView {
        return
            try SendView(
                id: FfiConverterOptionTypeSendId.read(from: &buf), 
                accessId: FfiConverterOptionString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                notes: FfiConverterOptionString.read(from: &buf), 
                key: FfiConverterOptionString.read(from: &buf), 
                newPassword: FfiConverterOptionString.read(from: &buf), 
                hasPassword: FfiConverterBool.read(from: &buf), 
                type: FfiConverterTypeSendType.read(from: &buf), 
                file: FfiConverterOptionTypeSendFileView.read(from: &buf), 
                text: FfiConverterOptionTypeSendTextView.read(from: &buf), 
                maxAccessCount: FfiConverterOptionUInt32.read(from: &buf), 
                accessCount: FfiConverterUInt32.read(from: &buf), 
                disabled: FfiConverterBool.read(from: &buf), 
                hideEmail: FfiConverterBool.read(from: &buf), 
                revisionDate: FfiConverterTypeDateTime.read(from: &buf), 
                deletionDate: FfiConverterTypeDateTime.read(from: &buf), 
                expirationDate: FfiConverterOptionTypeDateTime.read(from: &buf), 
                emails: FfiConverterSequenceString.read(from: &buf), 
                authType: FfiConverterTypeAuthType.read(from: &buf)
        )
    }

    public static func write(_ value: SendView, into buf: inout [UInt8]) {
        FfiConverterOptionTypeSendId.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.accessId, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.notes, into: &buf)
        FfiConverterOptionString.write(value.key, into: &buf)
        FfiConverterOptionString.write(value.newPassword, into: &buf)
        FfiConverterBool.write(value.hasPassword, into: &buf)
        FfiConverterTypeSendType.write(value.type, into: &buf)
        FfiConverterOptionTypeSendFileView.write(value.file, into: &buf)
        FfiConverterOptionTypeSendTextView.write(value.text, into: &buf)
        FfiConverterOptionUInt32.write(value.maxAccessCount, into: &buf)
        FfiConverterUInt32.write(value.accessCount, into: &buf)
        FfiConverterBool.write(value.disabled, into: &buf)
        FfiConverterBool.write(value.hideEmail, into: &buf)
        FfiConverterTypeDateTime.write(value.revisionDate, into: &buf)
        FfiConverterTypeDateTime.write(value.deletionDate, into: &buf)
        FfiConverterOptionTypeDateTime.write(value.expirationDate, into: &buf)
        FfiConverterSequenceString.write(value.emails, into: &buf)
        FfiConverterTypeAuthType.write(value.authType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendView_lift(_ buf: RustBuffer) throws -> SendView {
    return try FfiConverterTypeSendView.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendView_lower(_ value: SendView) -> RustBuffer {
    return FfiConverterTypeSendView.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Indicates the authentication strategy to use when accessing a Send
 */

public enum AuthType: UInt8, Equatable, Hashable {
    
    /**
     * Email-based OTP authentication
     */
    case email = 0
    /**
     * Password-based authentication
     */
    case password = 1
    /**
     * No authentication required
     */
    case none = 2





}

#if compiler(>=6)
extension AuthType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAuthType: FfiConverterRustBuffer {
    typealias SwiftType = AuthType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AuthType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .email
        
        case 2: return .password
        
        case 3: return .none
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AuthType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .email:
            writeInt(&buf, Int32(1))
        
        
        case .password:
            writeInt(&buf, Int32(2))
        
        
        case .none:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthType_lift(_ buf: RustBuffer) throws -> AuthType {
    return try FfiConverterTypeAuthType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthType_lower(_ value: AuthType) -> RustBuffer {
    return FfiConverterTypeAuthType.lower(value)
}



public enum CreateSendError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Api(message: String)
    
    case Crypto(message: String)
    
    case EmptyEmailList(message: String)
    
    case MissingField(message: String)
    
    case Repository(message: String)
    
    case SendParse(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CreateSendError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCreateSendError: FfiConverterRustBuffer {
    typealias SwiftType = CreateSendError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CreateSendError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Api(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Crypto(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .EmptyEmailList(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .MissingField(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .Repository(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .SendParse(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CreateSendError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Api(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Crypto(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .EmptyEmailList(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .MissingField(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .Repository(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .SendParse(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreateSendError_lift(_ buf: RustBuffer) throws -> CreateSendError {
    return try FfiConverterTypeCreateSendError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreateSendError_lower(_ value: CreateSendError) -> RustBuffer {
    return FfiConverterTypeCreateSendError.lower(value)
}


public enum EditSendError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case ItemNotFound(message: String)
    
    case Crypto(message: String)
    
    case Api(message: String)
    
    case EmptyEmailList(message: String)
    
    case MissingField(message: String)
    
    case Repository(message: String)
    
    case Uuid(message: String)
    
    case SendParse(message: String)
    
    case IdMismatch(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension EditSendError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEditSendError: FfiConverterRustBuffer {
    typealias SwiftType = EditSendError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EditSendError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ItemNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Crypto(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Api(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .EmptyEmailList(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .MissingField(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .Repository(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .Uuid(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .SendParse(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .IdMismatch(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EditSendError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .ItemNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Crypto(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Api(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .EmptyEmailList(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .MissingField(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .Repository(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .Uuid(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .SendParse(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .IdMismatch(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEditSendError_lift(_ buf: RustBuffer) throws -> EditSendError {
    return try FfiConverterTypeEditSendError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEditSendError_lower(_ value: EditSendError) -> RustBuffer {
    return FfiConverterTypeEditSendError.lower(value)
}


public enum GetSendError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case ItemNotFound(message: String)
    
    case Crypto(message: String)
    
    case MissingField(message: String)
    
    case Repository(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension GetSendError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGetSendError: FfiConverterRustBuffer {
    typealias SwiftType = GetSendError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GetSendError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ItemNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Crypto(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .MissingField(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .Repository(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: GetSendError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .ItemNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Crypto(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .MissingField(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .Repository(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGetSendError_lift(_ buf: RustBuffer) throws -> GetSendError {
    return try FfiConverterTypeGetSendError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGetSendError_lower(_ value: GetSendError) -> RustBuffer {
    return FfiConverterTypeGetSendError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Type-safe authentication method for a Send, including the authentication data.
 * This ensures that password and email authentication are mutually exclusive.
 */

public enum SendAuthType: Equatable, Hashable {
    
    /**
     * No authentication required
     */
    case none
    /**
     * Password-based authentication
     */
    case password(
        /**
         * The password required to access the Send
         */password: String
    )
    /**
     * Email-based OTP authentication
     */
    case emails(
        /**
         * List of email addresses that will receive OTP codes
         */emails: [String]
    )





}

#if compiler(>=6)
extension SendAuthType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendAuthType: FfiConverterRustBuffer {
    typealias SwiftType = SendAuthType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendAuthType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .none
        
        case 2: return .password(password: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .emails(emails: try FfiConverterSequenceString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SendAuthType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .none:
            writeInt(&buf, Int32(1))
        
        
        case let .password(password):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(password, into: &buf)
            
        
        case let .emails(emails):
            writeInt(&buf, Int32(3))
            FfiConverterSequenceString.write(emails, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendAuthType_lift(_ buf: RustBuffer) throws -> SendAuthType {
    return try FfiConverterTypeSendAuthType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendAuthType_lower(_ value: SendAuthType) -> RustBuffer {
    return FfiConverterTypeSendAuthType.lower(value)
}



/**
 * Generic error type for send decryption errors
 */
public enum SendDecryptError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Crypto(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SendDecryptError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendDecryptError: FfiConverterRustBuffer {
    typealias SwiftType = SendDecryptError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendDecryptError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Crypto(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SendDecryptError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Crypto(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendDecryptError_lift(_ buf: RustBuffer) throws -> SendDecryptError {
    return try FfiConverterTypeSendDecryptError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendDecryptError_lower(_ value: SendDecryptError) -> RustBuffer {
    return FfiConverterTypeSendDecryptError.lower(value)
}


/**
 * Generic error type for send decryption errors
 */
public enum SendDecryptFileError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Decrypt(message: String)
    
    case Io(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SendDecryptFileError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendDecryptFileError: FfiConverterRustBuffer {
    typealias SwiftType = SendDecryptFileError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendDecryptFileError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Decrypt(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Io(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SendDecryptFileError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Decrypt(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Io(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendDecryptFileError_lift(_ buf: RustBuffer) throws -> SendDecryptFileError {
    return try FfiConverterTypeSendDecryptFileError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendDecryptFileError_lower(_ value: SendDecryptFileError) -> RustBuffer {
    return FfiConverterTypeSendDecryptFileError.lower(value)
}


/**
 * Generic error type for send encryption errors.
 */
public enum SendEncryptError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Crypto(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SendEncryptError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendEncryptError: FfiConverterRustBuffer {
    typealias SwiftType = SendEncryptError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendEncryptError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Crypto(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SendEncryptError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Crypto(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendEncryptError_lift(_ buf: RustBuffer) throws -> SendEncryptError {
    return try FfiConverterTypeSendEncryptError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendEncryptError_lower(_ value: SendEncryptError) -> RustBuffer {
    return FfiConverterTypeSendEncryptError.lower(value)
}


/**
 * Generic error type for send encryption errors.
 */
public enum SendEncryptFileError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Encrypt(message: String)
    
    case Io(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SendEncryptFileError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendEncryptFileError: FfiConverterRustBuffer {
    typealias SwiftType = SendEncryptFileError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendEncryptFileError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Encrypt(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Io(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SendEncryptFileError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Encrypt(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Io(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendEncryptFileError_lift(_ buf: RustBuffer) throws -> SendEncryptFileError {
    return try FfiConverterTypeSendEncryptFileError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendEncryptFileError_lower(_ value: SendEncryptFileError) -> RustBuffer {
    return FfiConverterTypeSendEncryptFileError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * The type of Send, either text or file
 */

public enum SendType: UInt8, Equatable, Hashable {
    
    /**
     * Text-based send
     */
    case text = 0
    /**
     * File-based send
     */
    case file = 1





}

#if compiler(>=6)
extension SendType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendType: FfiConverterRustBuffer {
    typealias SwiftType = SendType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .text
        
        case 2: return .file
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SendType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .text:
            writeInt(&buf, Int32(1))
        
        
        case .file:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendType_lift(_ buf: RustBuffer) throws -> SendType {
    return try FfiConverterTypeSendType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendType_lower(_ value: SendType) -> RustBuffer {
    return FfiConverterTypeSendType.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSendFile: FfiConverterRustBuffer {
    typealias SwiftType = SendFile?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSendFile.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSendFile.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSendFileView: FfiConverterRustBuffer {
    typealias SwiftType = SendFileView?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSendFileView.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSendFileView.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSendText: FfiConverterRustBuffer {
    typealias SwiftType = SendText?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSendText.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSendText.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSendTextView: FfiConverterRustBuffer {
    typealias SwiftType = SendTextView?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSendTextView.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSendTextView.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDateTime: FfiConverterRustBuffer {
    typealias SwiftType = DateTime?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDateTime.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDateTime.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeEncString: FfiConverterRustBuffer {
    typealias SwiftType = EncString?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeEncString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeEncString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSendId: FfiConverterRustBuffer {
    typealias SwiftType = SendId?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSendId.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSendId.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}


/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias SendId = Uuid

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendId: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendId {
        return try FfiConverterTypeUuid.read(from: &buf)
    }

    public static func write(_ value: SendId, into buf: inout [UInt8]) {
        return FfiConverterTypeUuid.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> SendId {
        return try FfiConverterTypeUuid_lift(value)
    }

    public static func lower(_ value: SendId) -> RustBuffer {
        return FfiConverterTypeUuid_lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendId_lift(_ value: RustBuffer) throws -> SendId {
    return try FfiConverterTypeSendId.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendId_lower(_ value: SendId) -> RustBuffer {
    return FfiConverterTypeSendId.lower(value)
}


private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_bitwarden_send_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }

    uniffiEnsureBitwardenCoreInitialized()
    uniffiEnsureBitwardenCryptoInitialized()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureBitwardenSendInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all